name: auth
description: Auth feature package for BlogStore.
version: 0.1.0
publish_to: 'none'

resolution: workspace

environment:
  sdk: '^3.11.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  domain:
  core_ui:
  l10n:
  bloc_signals_flutter: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
