name: domain
description: Enterprise domain entities, interfaces, and contracts.
version: 0.1.0
publish_to: 'none'

resolution: workspace

environment:
  sdk: '^3.11.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.24.0
